name: slack-notify
inputs:
  status:
    required: false
    default: "failure"
  slack_incoming_url:
    required: true
  app:
    required: true
  image:
    required: false
    default: "-"
runs:
  using: "composite"
  steps:
    - name: Send Slack
      shell: bash
      run: |
        if [ "${{ inputs.status }}" = "success" ]; then
          EMOTICON="✅"
        else
          EMOTICON="⛔"
        fi

        MSG="{ \"text\":\">${EMOTICON} workflow (<https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}|${GITHUB_WORKFLOW}>) in <https://github.com/${GITHUB_REPOSITORY}|${GITHUB_REPOSITORY}>\n><https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks|${GITHUB_JOB}> job ${{ inputs.status }}, branch=\`${GITHUB_REF#refs/heads/}\`, app=\`"${{ inputs.app }}"\`, image=\`"${{ inputs.image }}"\`\"}"

         curl -X POST -H 'Content-type: application/json' --data "${MSG}" "${{ inputs.slack_incoming_url }}"
